const std = @import("std");
const page = @import("register_page.zig");
const bitflags = @import("bitflags.zig");

pub const registers = page.RegisterPage.init();

pub const instruction = struct {
    decompile: [24]u8, //decompile of the instruction for debugging
    operandLength: u8, //length of the operand we're working with
    execute: *const fn (anytype) void, //callback to the actual instruction, with pointer to anyopaque type for variability

    pub fn init(decomp: []const u8, opLength: u8, execute: *const fn (anytype) void) instruction {
        return instruction{ .decompile = decomp, .operandLength = opLength, .execute = &execute };
    }
};

pub const instructions: [256]instruction = .{
    instruction.init("NOP", 0, &nop), //0x00
    instruction.init("LD BC, 0x%04X", 2, &ld_bc_nn), //0x01
    instruction.init("LD (BC), A", 0, &ld_bcp_a), //0x02
    instruction.init("INC BC", 0, &nop),
    instruction.init("INC B", 0, &nop),
    instruction.init("DEC B", 0, &nop),
    instruction.init("LD B, 0x%02X", 0, &nop),
    instruction.init("RLCA", 0, &nop),
    instruction.init("LD (0x%02X)", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
    instruction.init("", 0, &nop),
};

//0x00
fn nop() void {}

//0x01
//load from immediate 16
fn ld_bc_nn(operand: u16) void {
    registers.write16(page.r16.BC, operand);
}

//0x02
//don't have to be unique, can't make generic load function
fn ld_bcp_a() void {
    registers.write16(page.r16.BC, registers.read(page.r8.A));
}
