const std = @import("std");
const page = @import("register_page.zig");
const bitflags = @import("bitflags.zig");

const registers = page.RegisterPage.init();

const instruction = struct {
    decompile: [24]u8, //decompile of the instruction for debugging
    operandLength: u8, //length of the operand we're working with
    execute: *const fn (*anyopaque) void, //callback to the actual instruction, with pointer to anyopaque type for variability
};

const instructions: [256]instruction = .{
    instruction{ "NOP", 0, &nop }, //0x00
    instruction{ "LD BC, 0x%04X", 2, &ld_bc_nn }, //0x01
    instruction{ "LD (BC), A", 0, &ld_bcp_a },
    instruction{ "INC BC", 0, &nop },
    instruction{ "INC B", 0, &nop },
    instruction{ "DEC B", 0, &nop },
    instruction{ "LD B, 0x%02X", 0, &nop },
    instruction{ "RLCA", 0, &nop },
    instruction{ "LD (0x%02X)", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
    instruction{ "", 0, &nop },
};

//0x00
fn nop() void {}

//0x01
//load from immediate 16
fn ld_bc_nn(operand: u16) void {
    registers.write16(page.r16.BC, operand);
}

//0x02
//don't have to be unique, can't make generic load function
fn ld_bcp_a() void {
    registers.write16(page.r16.BC, registers.read(page.r8.A));
}
